# -*- coding: utf-8 -*-
"""StackQ-2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZwH0IcaQmqyPsyYkqL2eNYh3AqIbTsdP

Given an input string, reverse the string word by word
"""

def reverse_word(s):
    listWords = s.split(' ')
    m = []
    for w in range(len(listWords)-1,-1,-1):
        m.append(listWords[w])
    print(m)
    print(' '.join(m))
        

s = "i like this program very much"
reverse_word(s)